### ISSUE TITLE
在 Windows11 系统下，字体不生效

### ISSUE THREAD

**Issue by XinLi0111** [TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji#1]
已关闭其他字体插件。默认主题和 Asri 主题都不生效

**Comment by TCOTC** [comment]
我这里没问题

1. 字体需要设置为 默认：
![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/78434827/a546ab4e-8bfc-4009-ae7d-41bc33f83db0)
2. 同时只能启用一个字体 & emoji 插件
![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/78434827/8ea3702f-290d-406a-a86a-f30f623e6e22)
3. 你的是什么设备？

**Comment by XinLi0111** [comment]
是的，字体默认，没有开启其他字体插件。设备：windows 11
![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/31495943/f5fd45d2-6483-45ec-8665-9e5b2ee00646)
![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/31495943/4622b7f2-bb9f-44e3-8572-2323c0542561)

**Comment by TCOTC** [comment]
我这里定位不到问题，你先新建一个工作空间试试看行不行？

**Comment by TCOTC** [comment]
以及重启一下思源看看生不生效

**Comment by XinLi0111** [comment]
![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/31495943/e99e08f6-2da3-4e1c-b49a-266f98760844)
新建工作空间，并重启后的状态。只安装了这一个插件

**Comment by XinLi0111** [comment]
![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/31495943/b9ea498c-3494-4591-91a3-48c158474764)
控制台报错

**Comment by TCOTC** [comment]
@XinLi0111 右键控制台空白区域，另存文本文档，然后复制里面的内容发给我看看

![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/78434827/37a18d54-d8a1-4f55-975d-3d56f98c805b)

**Comment by XinLi0111** [comment]
```
Failed to decode downloaded font: <URL>
Failed to decode downloaded font: <URL>
Failed to decode downloaded font: <URL>
Failed to decode downloaded font: <URL>
Failed to decode downloaded font: <URL>
Failed to decode downloaded font: <URL>
app/:1 Failed to decode downloaded font: http://127.0.0.1:55192/plugins/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/LXGWWenKaiGB-Regular.ttf
app/:1 Failed to decode downloaded font: http://127.0.0.1:55192/plugins/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/LXGWWenKaiGB-Regular.ttf
app/:1 Failed to decode downloaded font: http://127.0.0.1:55192/plugins/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/LXGWWenKaiGB-Regular.ttf
main.fc3b2ad90425a5fb5e6c.js:3585 Failed to decode downloaded font: http://127.0.0.1:55192/plugins/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/LXGWWenKaiGB-Regular.ttf
of @ main.fc3b2ad90425a5fb5e6c.js:3585
main.fc3b2ad90425a5fb5e6c.js:3585 Failed to decode downloaded font: http://127.0.0.1:55192/plugins/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/LXGWWenKaiGB-Regular.ttf
of @ main.fc3b2ad90425a5fb5e6c.js:3585
main.fc3b2ad90425a5fb5e6c.js:3585 Failed to decode downloaded font: http://127.0.0.1:55192/plugins/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/LXGWWenKaiGB-Regular.ttf
of @ main.fc3b2ad90425a5fb5e6c.js:3585
Vt @ main.fc3b2ad90425a5fb5e6c.js:3585
resize @ main.fc3b2ad90425a5fb5e6c.js:4124
（匿名） @ main.fc3b2ad90425a5fb5e6c.js:4149
（匿名） @ main.fc3b2ad90425a5fb5e6c.js:4149
setTimeout（异步）
Jt @ main.fc3b2ad90425a5fb5e6c.js:4149
（匿名） @ main.fc3b2ad90425a5fb5e6c.js:6608
OTS parsing error: cmap: Failed to parse table
OTS parsing error: cmap: Failed to parse table
OTS parsing error: cmap: Failed to parse table
OTS parsing error: cmap: Failed to parse table
OTS parsing error: cmap: Failed to parse table
OTS parsing error: cmap: Failed to parse table
app/:1 OTS parsing error: cmap: Failed to parse table
app/:1 OTS parsing error: cmap: Failed to parse table
app/:1 OTS parsing error: cmap: Failed to parse table
main.fc3b2ad90425a5fb5e6c.js:3585 OTS parsing error: cmap: Failed to parse table
of @ main.fc3b2ad90425a5fb5e6c.js:3585
main.fc3b2ad90425a5fb5e6c.js:3585 OTS parsing error: cmap: Failed to parse table
of @ main.fc3b2ad90425a5fb5e6c.js:3585
main.fc3b2ad90425a5fb5e6c.js:3585 OTS parsing error: cmap: Failed to parse table
of @ main.fc3b2ad90425a5fb5e6c.js:3585
Vt @ main.fc3b2ad90425a5fb5e6c.js:3585
resize @ main.fc3b2ad90425a5fb5e6c.js:4124
（匿名） @ main.fc3b2ad90425a5fb5e6c.js:4149
（匿名） @ main.fc3b2ad90425a5fb5e6c.js:4149
setTimeout（异步）
Jt @ main.fc3b2ad90425a5fb5e6c.js:4149
（匿名） @ main.fc3b2ad90425a5fb5e6c.js:6608
```

**Comment by TCOTC** [comment]
控制台报错的右边点击看看显示什么？

比如这些：

![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/78434827/35db8cde-2a3c-44a3-8d4d-4b3a729ad4f2)

**Comment by XinLi0111** [comment]
![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/31495943/e3ab2d39-debe-47be-ba84-bbf91a9f415b)
都是这一行

**Comment by TCOTC** [comment]
@XinLi0111 集市上架了 [v0.2.0](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/releases/tag/v0.2.0) ，你更新之后重启思源，再看看行不行

**Comment by XinLi0111** [comment]
还是不行。鸿蒙字体的有效果，这个就没有，我自己设置电脑本地的字体就可以。我的两台win11系统分别是intel 和AMD 的都是霞鹜不行，鸿蒙行。
![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/31495943/89abd5a4-19f2-4ba9-b695-79c481f4e0f3)

**Comment by XinLi0111** [comment]
![image](https://github.com/TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji/assets/31495943/2b290dbf-902c-493c-b491-66968c093bca)

**Comment by TCOTC** [comment]
我改了一下代码，所以无论是否成功加载都不会在「网络」里显示字体了。所以跟这个应该没有关系

**Comment by TCOTC** [comment]
实在不行就只能下载字体安装到电脑之后在思源里用了 https://github.com/lxgw/LxgwWenkaiGB/releases/download/v1.330/LXGWWenKaiGB-Regular.ttf

**Comment by XinLi0111** [comment]
嗯嗯，谢谢了

**Comment by TCOTC** [comment]
@XinLi0111 麻烦帮忙看看集市刚刚更新的 v0.2.2 版本行不行

**Comment by XinLi0111** [comment]
可以了，太赞了。

还有个不情之请。这个字体默认笔画有点细，我之前用的是那个“屏幕阅读版”，整体是将笔画略微加粗了一点，您看看能不能再出个霞鹜屏幕阅读版的字体插件。
https://github.com/lxgw/LxgwWenKai-Screen

**Comment by TCOTC** [comment]
上架两个霞鹜文楷字体感觉有点怪，你可以直接以我的仓库为模板改一改（换字体文件、改 index.css ）然后自己用

**Comment by TCOTC** [comment]
对了，plugin.json 和插件文件夹的名称也要改，不能和已有的插件相同

**Comment by gagmeng** [comment]
> 可以了，太赞了。
> 
> 还有个不情之请。这个字体默认笔画有点细，我之前用的是那个“屏幕阅读版”，整体是将笔画略微加粗了一点，您看看能不能再出个霞鹜屏幕阅读版的字体插件。 https://github.com/lxgw/LxgwWenKai-Screen

请问一下后面是怎么解决的，我也碰到了同样的问题

**Comment by XinLi0111** [comment]
> > 可以了，太赞了。
> > 还有个不情之请。这个字体默认笔画有点细，我之前用的是那个“屏幕阅读版”，整体是将笔画略微加粗了一点，您看看能不能再出个霞鹜屏幕阅读版的字体插件。 https://github.com/lxgw/LxgwWenKai-Screen
> 
> 请问一下后面是怎么解决的，我也碰到了同样的问题
[siyuan-XWWKGB.zip](https://github.com/user-attachments/files/18193307/siyuan-XWWKGB.zip)
解压到思源的插件目录里试试。`<siyuan>/data/plugins/`

**Comment by TCOTC** [comment]
@XinLi0111 现在发现确实有点细，v1.0.0 版本我改成屏幕阅读版了
