### ISSUE TITLE
请问不能解码是怎么回事？ Failed to decode downloaded font 

### ISSUE THREAD

**Issue by IAliceBobI** [TCOTC/siyuan-ttf-LXGWWenKaiGB-and-Twemoji#2]
![image](https://github.com/user-attachments/assets/aaaf710f-4bb1-42fb-bbc5-5198af8026e9)

**Comment by TCOTC** [comment]
我也搞不懂这个字体是怎么回事，不过能正常用就行了

**Comment by IAliceBobI** [comment]
你的另外一个字体插件没有这个问题。

**Comment by TCOTC** [comment]
我也发现了。感觉是字体文件的问题，但我对这方面没什么了解。

**Comment by IAliceBobI** [comment]
woff2  应该都是这个格式的问题，去掉这个格式可以吗？

**Comment by IAliceBobI** [comment]
字体文件损坏
文件损坏：字体文件本身可能已经损坏，导致浏览器无法正确解析。

不兼容的格式：某些浏览器可能不支持特定的字体格式（如 .woff2），或者字体文件的格式不正确。

**Comment by IAliceBobI** [comment]
woff2  这个反正也加载不了，我看没有这个也能正常工作，还不如去掉这个。

**Comment by IAliceBobI** [comment]
保持控制台干净一点，方便开发者查看信息。
